# Generated by Django 4.2.4 on 2024-05-17 05:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                ("icono", models.ImageField(upload_to="", verbose_name="Icono")),
                ("contenido", ckeditor.fields.RichTextField(verbose_name="Contenido")),
            ],
        ),
    ]
