# Generated by Django 4.2.4 on 2024-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geeksapp", "0002_servicios_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicios",
            options={"verbose_name": "Servicio", "verbose_name_plural": "Servicios"},
        ),
        migrations.AddField(
            model_name="servicios",
            name="portada",
            field=models.ImageField(null=True, upload_to="", verbose_name="Portada"),
        ),
    ]
