# Generated by Django 4.2.4 on 2024-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geeksapp", "0004_alter_servicios_icono_alter_servicios_portada"),
    ]

    operations = [
        migrations.CreateModel(
            name="Informacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(max_length=40, verbose_name="Número de teléfono"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo Electrónico"
                    ),
                ),
                ("web", models.CharField(max_length=50, verbose_name="Página web")),
            ],
        ),
    ]
